// Generated by https://quicktype.io

export interface InfoPlayers {
  id:            string;
  accountId:     string;
  puuid:         string;
  profileIconId: number;
  revisionDate:  number;
  summonerLevel: number;
}
