// Generated by https://quicktype.io

export interface InfoPlayers {
  leagueId:     string;
  queueType:    string;
  tier:         string;
  rank:         string;
  summonerId:   string;
  puuid:        string;
  leaguePoints: number;
  wins:         number;
  losses:       number;
  veteran:      boolean;
  inactive:     boolean;
  freshBlood:   boolean;
  hotStreak:    boolean;
}
